import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <footer className="text-sm text-center py-4">
          <p>
            Made with 🩷 by <a className="text-blue-500">6410406860 (Non)</a>,{" "}
            <a className="text-blue-500">6410406711 (Toey)</a>,{" "}
            <a className="text-blue-500">6410406649 (Pam)</a> for 01418334(66-2)
            Compiler Techniques
          </p>
        </footer>
      </body>
    </html>
  );
}
